In [1]:
import numpy as np

In [14]:
a = np.random.normal(0,1,size=(10,5))

In [15]:
a

array([[-0.64217093,  0.13493384,  0.52013981, -1.1062197 ,  0.57811165],
       [ 0.80546033, -1.12449918, -0.86140561,  1.15299046,  1.37691841],
       [ 0.45501263, -0.57142833,  0.85163726,  0.28062816,  0.57810697],
       [-2.28845188, -1.35588346,  0.03226911,  0.01290772, -0.00825621],
       [-0.79178337,  0.98445665, -0.44722416,  0.04204186,  0.35469515],
       [ 0.57572285,  1.41189982, -0.74719528,  0.39363704, -0.22125664],
       [-0.11635141,  0.1399765 ,  0.55416598,  1.25413515,  0.41667215],
       [ 1.09366527, -1.41925682,  0.92194123, -0.58493184,  0.07146599],
       [-0.12662434, -0.08363641,  0.3979495 , -1.64070295,  0.65981419],
       [-0.82508145, -1.71056284, -0.27628643, -0.18179311, -2.15978399]])

In [16]:
h = np.argmax(a, axis=1)

In [17]:
h

array([4, 4, 2, 2, 1, 1, 3, 0, 4, 3])

In [18]:
a[:,:] = 0

In [19]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
list(zip(range(10), h))

[(0, 4),
 (1, 4),
 (2, 2),
 (3, 2),
 (4, 1),
 (5, 1),
 (6, 3),
 (7, 0),
 (8, 4),
 (9, 3)]

In [25]:
a[range(10), h] = 1

In [26]:
a

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [9]:
a

array([[1, 1, 0],
       [0, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]])

In [10]:
b

array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [40]:
import pandas as pd
df = pd.read_csv('/home/jupyter/stormbreaker/deep_learning_models/data/attribute_extraction/color_category/out_urls.csv')

In [41]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'item_id', 'title',
       'long_description', 'short_description', 'brand', 'product_type',
       'image_urls', 'image_url_types', 'color_category', 'image_path'],
      dtype='object')

In [42]:
df.image_path[0]

'/home/jupyter/stormbreaker/deep_learning_models/data/attribute_extraction/color_category/downloaded_images/554a35b74ce3472a154d52d624d4ddba.jpg'

In [38]:
df['image_path'] = df['image_path'].str.replace('downloaded_images/color_images','downloaded_images')

In [39]:
df.to_csv('/home/jupyter/stormbreaker/deep_learning_models/data/attribute_extraction/color_category/out_urls.csv')